# Generated by Django 4.1.7 on 2024-02-28 09:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('rest_name', models.CharField(max_length=180)),
                ('rest_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant_details',
            fields=[
                ('rest_name', models.CharField(max_length=180)),
                ('rest_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('location', models.CharField(max_length=180)),
                ('description', models.TextField(default='Description not available')),
                ('image', models.URLField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_id', models.IntegerField()),
                ('image_url', models.URLField(max_length=250)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_email', models.CharField(default='abc@email.com', max_length=180, primary_key=True, serialize=False)),
                ('resy_email', models.CharField(default='abc@email.com', max_length=180)),
                ('resy_pwd', models.CharField(default='abc', max_length=180)),
                ('user_name', models.CharField(default='abc', max_length=180)),
                ('user_token', models.TextField(default='abc')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=180)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(blank=True, default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation_request',
            fields=[
                ('booking_id', models.TextField(default='abc', primary_key=True, serialize=False)),
                ('rest_name', models.CharField(max_length=180)),
                ('rest_id', models.IntegerField()),
                ('base_img_url', models.URLField(default='images/img_rectangle31_230x230.png', max_length=250)),
                ('rating', models.FloatField(blank=True, default=4.5, null=True)),
                ('date', models.DateField()),
                ('from_time', models.TimeField(default=datetime.time(8, 0))),
                ('to_time', models.TimeField(default=datetime.time(8, 0))),
                ('number_of_guests', models.IntegerField()),
                ('booking_available_till', models.DateField()),
                ('is_booking_date_active', models.BooleanField(default=False)),
                ('booking_status', models.CharField(default='Pending', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_email', models.ForeignKey(default='abc@email.com', on_delete=django.db.models.deletion.CASCADE, to='resy.user')),
            ],
        ),
        migrations.CreateModel(
            name='Booking_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_status', models.CharField(default='Pending', max_length=100)),
                ('reservation_id', models.TextField(default='abc')),
                ('reservation_cnf_token', models.TextField(default='abc')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resy.reservation_request')),
            ],
        ),
    ]
