# Generated by Django 4.1.7 on 2023-03-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("resy", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Reservation_request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rest_name", models.CharField(max_length=180)),
                ("date", models.DateField()),
                ("start_time_slot", models.TimeField()),
                ("end_time_slot", models.TimeField()),
                (
                    "sitting_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("number_of_guests", models.IntegerField()),
            ],
        )
    ]
