# Generated by Django 4.1.7 on 2023-03-20 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("resy", "0002_reservation_request")]

    operations = [
        migrations.RemoveField(model_name="reservation_request", name="end_time_slot"),
        migrations.RemoveField(model_name="reservation_request", name="sitting_type"),
        migrations.RemoveField(
            model_name="reservation_request", name="start_time_slot"
        ),
    ]
