# Generated by Django 4.1.7 on 2023-03-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("resy", "0004_reservation_request_is_booking_date_active")]

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rest_name", models.CharField(max_length=180)),
                ("rest_id", models.IntegerField()),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
        )
    ]
