# Generated by Django 4.1.7 on 2023-03-23 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("resy", "0005_restaurant")]

    operations = [
        migrations.RenameField(
            model_name="restaurant", old_name="updated", new_name="updated_at"
        )
    ]
