# Generated by Django 4.1.7 on 2023-03-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("resy", "0007_alter_restaurant_created_at")]

    operations = [
        migrations.AddField(
            model_name="reservation_request",
            name="rest_id",
            field=models.IntegerField(default=0),
        )
    ]
