# Generated by Django 4.1.7 on 2023-03-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("resy", "0008_reservation_request_rest_id")]

    operations = [
        migrations.AddField(
            model_name="reservation_request",
            name="booking_available_till",
            field=models.DateField(default="2025-01-01"),
        )
    ]
