# Generated by Django 4.1.7 on 2023-03-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resy', '0010_alter_reservation_request_booking_available_till'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation_request',
            name='booking_available_till',
            field=models.DateField(),
        ),
    ]
