# Generated by Django 4.1.7 on 2023-05-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resy', '0011_alter_reservation_request_booking_available_till'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='id',
        ),
        migrations.AlterField(
            model_name='reservation_request',
            name='rest_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rest_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
