# Generated by Django 4.1.7 on 2023-05-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resy', '0012_remove_restaurant_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation_request',
            name='booking_status',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AddField(
            model_name='reservation_request',
            name='resy_email',
            field=models.CharField(default='abc', max_length=180),
        ),
        migrations.AddField(
            model_name='reservation_request',
            name='resy_pwd',
            field=models.CharField(default='abc', max_length=180),
        ),
        migrations.AddField(
            model_name='reservation_request',
            name='user_token',
            field=models.TextField(default='abc'),
        ),
    ]
