# Generated by Django 4.1.7 on 2023-06-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resy', '0013_reservation_request_booking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation_request',
            name='booking_id',
            field=models.TextField(default='abc'),
        ),
    ]
