# Generated by Django 4.1.7 on 2023-06-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resy', '0014_reservation_request_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation_request',
            name='reservation_cnf_token',
            field=models.TextField(default='abc'),
        ),
        migrations.AddField(
            model_name='reservation_request',
            name='reservation_id',
            field=models.TextField(default='abc'),
        ),
    ]
