# Generated by Django 4.1.7 on 2023-06-14 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resy', '0015_reservation_request_reservation_cnf_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation_request',
            name='from_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='reservation_request',
            name='to_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
