# Generated by Django 4.1.7 on 2023-06-29 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resy', '0016_reservation_request_from_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resy_email', models.CharField(default='abc@email.com', max_length=180)),
                ('resy_pwd', models.CharField(default='abc', max_length=180)),
                ('user_name', models.CharField(default='abc', max_length=180)),
                ('user_email', models.CharField(default='abc@email.com', max_length=180)),
                ('user_token', models.TextField(default='abc')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='reservation_request',
            name='reservation_cnf_token',
        ),
        migrations.RemoveField(
            model_name='reservation_request',
            name='reservation_id',
        ),
        migrations.RemoveField(
            model_name='reservation_request',
            name='resy_email',
        ),
        migrations.RemoveField(
            model_name='reservation_request',
            name='resy_pwd',
        ),
        migrations.RemoveField(
            model_name='reservation_request',
            name='user_token',
        ),
        migrations.CreateModel(
            name='Booking_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_status', models.CharField(default='Pending', max_length=100)),
                ('reservation_id', models.TextField(default='abc')),
                ('reservation_cnf_token', models.TextField(default='abc')),
                ('booking_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resy.reservation_request')),
            ],
        ),
    ]
