# Generated by Django 4.1.7 on 2023-07-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resy', '0017_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_details',
            name='created_at',
            field=models.DateTimeField(default='2010-01-03 04:30:43'),
        ),
        migrations.AddField(
            model_name='booking_details',
            name='updated_at',
            field=models.DateTimeField(default='2010-01-03 04:30:43'),
        ),
        migrations.AddField(
            model_name='reservation_request',
            name='created_at',
            field=models.DateTimeField(default='2010-01-03 04:30:43'),
        ),
        migrations.AddField(
            model_name='reservation_request',
            name='updated_at',
            field=models.DateTimeField(default='2010-01-03 04:30:43'),
        ),
    ]
