# Generated by Django 4.1.7 on 2023-07-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resy', '0018_booking_details_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_details',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking_details',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reservation_request',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reservation_request',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
