# Generated by Django 4.1.7 on 2023-11-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resy', '0019_alter_booking_details_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant_details',
            fields=[
                ('rest_name', models.CharField(max_length=180)),
                ('rest_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('location', models.CharField(max_length=180)),
                ('description', models.TextField(default='Description not available')),
                ('image', models.URLField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_id', models.IntegerField()),
                ('image_url', models.URLField(max_length=250)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
