# Generated by Django 4.1.7 on 2024-02-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resy', '0020_restaurant_details_restaurant_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation_request',
            name='base_img_url',
            field=models.URLField(default='images/img_rectangle31_230x230.png', max_length=250),
        ),
        migrations.AddField(
            model_name='reservation_request',
            name='rating',
            field=models.FloatField(blank=True, default=4.5, null=True),
        ),
    ]
